server:
  port: 8762

#服务的名称
spring:
  application:
    name: zuul-service
  cloud:
    client:
      ipAddress: localhost

#指定注册中心地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  #在eureka中显示正确的IP地址
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}

zuul:
  host:
    socket-timeout-millis: 3000
    connect-timeout-millis: 3000

ribbon:
  ReadTimeout: 2000
  ConnectTimeout: 2000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 8000