server:
  port: 8084

#指定注册中心地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  #在eureka中显示正确的IP地址
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
#服务的名称
spring:
  application:
    name: order-service
  cloud:
    client:
      ipAddress: localhost

feign:
  client:
    config:
      default:
        connectTimeout: 3000
        readTimeout: 3000
  hystrix:
    enabled: true
    command:
      default:
        execution:
          isolation:
            thread:
              timeoutInMilliseconds: 3000

management:
  endpoints:
    web:
      exposure:
        include: "*"